travis:
  secure:
    BINSTAR_TOKEN: SHDsiFTG8J1SKoo5oUpb/Ymx28tU5/25m4oEr8nzFRNtP7hhue///QkX+oEuZrWz+nbUJ1WaI8ywWddglZDd7pcA9JlPut0PlPNG9HYFKB53XPzc1b0flNk2zKRtxc5ckEHq0mB2N5tJiNRk/NFPgIc+A0SRc6HvfLSvbuzRtZmDPrGgfUFvEzxxSwSoAImX6qv10O5B9ZSiKRbjci7ZmhVJRwzBMEAo+ruDd4Kq+AB9sOpaNgHPmQSxhndVBphJT1SoNtShemUzMme3fe3BW++oAgg7FY1GTnGEZAZ8dT/zLjX7kjy0d2676i25wsLtfg7rev6ipopShyMlGMLdxylDlBPcD0mhpKHYi4vYGCm6Zg1/7ROR3IKopnvq0PdXq4w8VhluNQIQxOcAi02GJjof8k3FRYRFJMFqFmzEIgrRc482H7nL1m09398Rt/TL0gaVTbyRJf9i0p7i93BcaV6NwacbgfiLKob0nRg77ijd/ISkkqjNn8aV4zs715jixwpzS+WuaPFHD5Hlw1WDwrlHUsKPUTBYniJtHYt+QKH6iy/UG0NkPlAa7P1jLKdGVA5O19EUEh/L3kGxJawmbcCBRz9VqkXMwQ+LBJsWKmrzsR/9BcJUw8TX4HDQiz4vUm5YQ8g68z/5PMW0xgj/3kxyT0dDgbSb+xSv3R2nHWg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
